### ISSUE TITLE
CSS: set vertical-align to text-top for #logs

### ISSUE THREAD

**Issue by artbikes** [rashidkpc/kibana2#50]
When viewing a large multi-line event the @source_host can be pushed off the screen. How about?:

``` css
#logs td {
word-wrap: break-word;
font-size: 11px;
vertical-align: text-top;
}
```
